version: "3.8"

services:
  nodered:
    image: nodered/node-red:latest-10
    ports:
      - 1880:1880/tcp
    volumes:
      - /mnt/nfs/nodered/data:/data
    deploy:
      replicas: 1
      update_config:
        order: stop-first
        failure_action: continue
